name: ci
on:
  push:
    branches:
      - ci
jobs:
  x86_64-windows-release:
    timeout-minutes: 120
    runs-on: windows-latest
    env:
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/x86_64-windows-release.ps1
